### ISSUE TITLE
Tag versions without the "v" prefix

### ISSUE THREAD

**Issue by kkostov** [divadretlaw/EmojiText#1]
Presently, Xcode does not support version tags with a "v" prefix (cf. https://forums.swift.org/t/support-for-v-prefixed-version-tags-in-spm-swift-playgrounds-for-ipad/54845/5) and as a result, it's only possible to depend on EmojiText by branch or a commit which is not always optimal.

Would it be possible to tag releases as semantic version numbers from now on? e.g. "v2.0.0" -> "2.0.0"

Thank you!

**Comment by divadretlaw** [comment]
Sure, I don't see why not. EmojiText is now available via the tags `2.0.0` and `2.0.1`, in addition to the existing tags (`v2.0.0` and `v2.0.1`). All future tags won't have the `v` prefix anymore.
