### ISSUE TITLE
Stress test

### ISSUE THREAD

**Issue by Dimillian** [divadretlaw/EmojiText#18]
This issue have been reported on Ice Cubes

https://github.com/Dimillian/IceCubesApp/issues/1738

If you want to have fun optimizing memory consumption. I haven't looked yet in detail, but the app is spiking around 700 MB of RAM instantly.

**Comment by divadretlaw** [comment]
Looks like the RAM issue and crash are separate issues. The crash seems to be because with that many emojis we run into concatenations limits of `Text`.

**Comment by divadretlaw** [comment]
Should be fixed with `3.2.0`. Tested in Ice Cubes App and I don't seem to crash on the mentioned post anymore.
