### ISSUE TITLE
Only one emoji is displayed when the same emoji are lined up

### ISSUE THREAD

**Issue by mironal** [divadretlaw/EmojiText#22]
If the same Emoji is lined up as follows, only one will be displayed.

`EmojiText(markdown: "Hello :mastodon: :mastodon:", emojis: emojis)`

I can work around this by specifying `.emojiOmitSpacesBetweenEmojis(false)`, but is this behavior expected?

<img width="1331" alt="image" src="https://github.com/divadretlaw/EmojiText/assets/537587/88c414e3-9c63-4550-86c3-f7cdf8042ac2">

**Comment by divadretlaw** [comment]
There doesn't seem to be a direct way to access the raw string (`mastodonmastodon`) from `AttributedString`, but I found a workaround that I'm not 100% sure about, but its already available on the `main` branch.

**Comment by divadretlaw** [comment]
Workaround is in `3.5.0`, please let me know in case there are other issues.

**Comment by mironal** [comment]
thanks!
