### ISSUE TITLE
Incorrect scaling with dynamic type

### ISSUE THREAD

**Issue by Tunous** [divadretlaw/EmojiText#27]
Emojis incorrectly scale when dynamic type size is larger than default. This can be reproduced in the sample app and affects both local and remote emojis. Additionally changing type size doesn't immediately update emojis but instead requires the view to be displayed again.

![Simulator Screenshot - iPhone 15 Pro - 2024-08-17 at 15 46 03](https://github.com/user-attachments/assets/b02dcb2f-8c72-4013-9c7d-592c871ad6ba)

Expected result would be emojis which have height equal to a line of text without overlapping.

**Comment by divadretlaw** [comment]
Thank you for bringing this to my attention, the emojis scale very wrongly with dynamic type and the fix seems rather easy, will be fixed in `4.1.0`

**Comment by Tunous** [comment]
Great, that was quick.
